#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${STATE_DIR:-${ROOT_DIR}/.state}"

CERT_DIR="${CERT_DIR:-${STATE_DIR}/certs}"
OUT_ENV="${OUT_ENV:-${STATE_DIR}/tls.env}"

CERT_NAME="${CERT_NAME:-localhost-wildcard}"

if ! command -v mkcert >/dev/null 2>&1; then
  echo "mkcert is required (https://github.com/FiloSottile/mkcert)" >&2
  exit 1
fi

mkdir -p "$CERT_DIR"

# Idempotent: installs local CA into trust store (may prompt for sudo depending on OS).
if ! mkcert -install >/dev/null 2>&1; then
  cat >&2 <<'EOF'
mkcert CA is not installed in the system trust store.

This script can still generate a certificate, but browsers/clients may not trust it
until you run:
  mkcert -install

Note: `mkcert -install` may require sudo and an interactive terminal.
EOF
fi

CERT_PEM="${CERT_DIR}/${CERT_NAME}.pem"
KEY_PEM="${CERT_DIR}/${CERT_NAME}-key.pem"

if [[ "${FORCE_TLS:-false}" != "true" && -f "$OUT_ENV" && -f "$CERT_PEM" && -f "$KEY_PEM" ]]; then
  echo "TLS material already present (set FORCE_TLS=true to regenerate):"
  echo "  cert: $CERT_PEM"
  echo "  env:  $OUT_ENV"
  exit 0
fi

# Extra explicit DNS names to include in the certificate SANs.
# Some TLS clients are picky about "*.localhost" wildcards.
EXTRA_DNS_NAMES="${EXTRA_DNS_NAMES:-mq.localhost grafana.localhost argocd.localhost}"

# Generate a certificate covering our local DNS scheme:
# - localhost: direct access
# - *.localhost: host-based ingress routing (mq.localhost, grafana.localhost)
# EXTRA_DNS_NAMES is a space-separated list of SANs that must be passed as
# separate arguments, so word splitting is intended here.
# shellcheck disable=SC2086
mkcert -cert-file "$CERT_PEM" -key-file "$KEY_PEM" \
  localhost "*.localhost" 127.0.0.1 ::1 ${EXTRA_DNS_NAMES} >/dev/null

TLS_CERT_STRING="$(base64 -w 0 < "$CERT_PEM")"
TLS_KEY_STRING="$(base64 -w 0 < "$KEY_PEM")"

cat > "$OUT_ENV" <<EOF
# Generated by scripts/mkcert-gen.sh
export TLS_CERT_STRING='${TLS_CERT_STRING}'
export TLS_KEY_STRING='${TLS_KEY_STRING}'
EOF

echo "Wrote cert: $CERT_PEM"
echo "Wrote key:  $KEY_PEM"
echo "Wrote env:  $OUT_ENV"
