apiVersion: messaging.kurator.dev/v1alpha1
kind: ChannelAuthRule
metadata:
  name: dev-app-addressmap
  namespace: kurator-system
spec:
  connectionRef:
    name: qm1
  channelName: DEV.APP.SVRCONN.0TLS
  ruleType: ADDRESSMAP
  address: "*"
  userSource: CHANNEL
  checkClient: REQUIRED
  description: Allows connection via APP channel
