{{- if and .Values.webhooks.enabled .Values.webhooks.certManager.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kurator.selfSignedIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kurator.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kurator.servingCertName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kurator.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  dnsNames:
    {{- $svc := include "kurator.webhookServiceName" . }}
    - {{ printf "%s.%s.svc" $svc .Release.Namespace }}
    - {{ printf "%s.%s.svc.cluster.local" $svc .Release.Namespace }}
  issuerRef:
    kind: Issuer
    name: {{ include "kurator.selfSignedIssuerName" . }}
  secretName: {{ .Values.webhooks.certManager.secretName }}
{{- end }}
