apiVersion: messaging.kurator.dev/v1alpha1
kind: AuthorityRecord
metadata:
  name: app-orders-get-put
spec:
  connectionRef:
    name: qm1
  profile: APP.ORDERS
  objectType: QUEUE
  principal: app
  authorities:
    - GET
    - PUT
