apiVersion: messaging.kurator.dev/v1alpha1
kind: ChannelAuthRule
metadata:
  name: dev-app-blockuser
spec:
  connectionRef:
    name: qm1
  channelName: DEV.APP.SVRCONN.0TLS
  ruleType: BLOCKUSER
  userList: nobody
  description: Deny privileged user IDs on the gitops sample channel
