controller:
  service:
    type: NodePort
    externalTrafficPolicy: Local
    httpPorts:
      - port: 80
        targetPort: http
        nodePort: 30080
    httpsPorts:
      - port: 443
        targetPort: https
        nodePort: 30443
